import {FormEvent,useEffect,useState} from'react'
import{AcademicYear,AcademicYearDraft,AcademicYearQuarter,createAcademicYear,createAcademicYearQuarter,deleteAcademicYearQuarter,listAcademicYears,updateAcademicYearQuarter}from'./academicYears'

const empty=():AcademicYearDraft=>({name:'',startsOn:'',endsOn:'',status:'planned'})
const labels={planned:'Запланирован',active:'Активный',completed:'Завершён'}
type PeriodDraft={name:string;startsOn:string;endsOn:string}
type PeriodEditor={year:AcademicYear;quarter?:AcademicYearQuarter}

export default function AcademicYearsView(){
 const[items,setItems]=useState<AcademicYear[]>([]),[draft,setDraft]=useState<AcademicYearDraft|null>(null),[periodEditor,setPeriodEditor]=useState<PeriodEditor|null>(null),[period,setPeriod]=useState<PeriodDraft>({name:'',startsOn:'',endsOn:''}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[dialogError,setDialogError]=useState('')
 useEffect(()=>{listAcademicYears().then(setItems).catch(e=>setError(e instanceof Error?e.message:'Ошибка загрузки')).finally(()=>setLoading(false))},[])
 async function saveYear(e:FormEvent){e.preventDefault();if(!draft)return;setSaving(true);setDialogError('');try{const value=await createAcademicYear(draft);setItems(v=>[value,...v]);setDraft(null)}catch(e){setDialogError(e instanceof Error?e.message:'Не удалось создать год')}finally{setSaving(false)}}
 function openPeriod(year:AcademicYear,quarter?:AcademicYearQuarter){setDialogError('');setPeriodEditor({year,quarter});setPeriod(quarter?{name:quarter.name,startsOn:quarter.startsOn,endsOn:quarter.endsOn}:{name:'',startsOn:year.startsOn,endsOn:year.endsOn})}
 async function savePeriod(e:FormEvent){e.preventDefault();if(!periodEditor)return;setSaving(true);setDialogError('');try{const value=periodEditor.quarter?await updateAcademicYearQuarter(periodEditor.quarter.id,period):await createAcademicYearQuarter(periodEditor.year.id,period);setItems(v=>v.map(y=>y.id!==periodEditor.year.id?y:{...y,quarters:periodEditor.quarter?y.quarters.map(q=>q.id===value.id?value:q):[...y.quarters,value]}));setPeriodEditor(null)}catch(e){setDialogError(e instanceof Error?e.message:'Не удалось сохранить период')}finally{setSaving(false)}}
 async function removePeriod(year:AcademicYear,quarter:AcademicYearQuarter){if(!window.confirm(`Удалить период «${quarter.name}»?`))return;setSaving(true);setError('');try{await deleteAcademicYearQuarter(quarter.id);setItems(v=>v.map(y=>y.id===year.id?{...y,quarters:y.quarters.filter(q=>q.id!==quarter.id)}:y))}catch(e){setError(e instanceof Error?e.message:'Не удалось удалить период')}finally{setSaving(false)}}
 return <div className="content-stack"><div className="content-heading"><div><p className="content-kicker">Учебный календарь</p><h2>Учебные годы</h2></div><button className="primary-action" onClick={()=>{setDialogError('');setDraft(empty())}}>+ Создать учебный год</button></div>{error&&<p className="content-error" role="alert">{error}</p>}{loading?<div className="empty-card">Загружаем…</div>:<div className="table-card table-scroll"><table className="roles-table"><thead><tr><th>Название</th><th>Период</th><th>Статус</th><th>Периоды</th><th/></tr></thead><tbody>{items.map(y=><tr key={y.id}><td><strong>{y.name}</strong></td><td>{y.startsOn} — {y.endsOn}</td><td>{labels[y.status]}</td><td><div className="academic-period-list">{y.quarters.map(q=><div className="academic-period" key={q.id}><span className="status-badge">{q.name}: {q.startsOn}—{q.endsOn}</span><button className="period-icon-action" aria-label={`Редактировать период ${q.name}`} title="Редактировать" onClick={()=>openPeriod(y,q)}>✎</button><button className="period-icon-action period-icon-action--danger" aria-label={`Удалить период ${q.name}`} title="Удалить" disabled={saving} onClick={()=>removePeriod(y,q)}>×</button></div>)}</div></td><td><button className="secondary-action" onClick={()=>openPeriod(y)}>+ Период</button></td></tr>)}</tbody></table></div>}{draft&&<Dialog title="Новый учебный год" close={()=>setDraft(null)} error={dialogError}><form className="role-form" onSubmit={saveYear}><label>Название<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><Dates value={draft} change={(k,v)=>setDraft({...draft,[k]:v})}/><label>Статус<select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as AcademicYearDraft['status']})}><option value="planned">Запланирован</option><option value="active">Активный</option><option value="completed">Завершён</option></select></label><Actions saving={saving}/></form></Dialog>}{periodEditor&&<Dialog title={`${periodEditor.quarter?'Редактировать':'Новый'} период · ${periodEditor.year.name}`} close={()=>setPeriodEditor(null)} error={dialogError}><form className="role-form" onSubmit={savePeriod}><label>Название<input aria-label="Название периода" required maxLength={100} value={period.name} onChange={e=>setPeriod({...period,name:e.target.value})}/></label><Dates value={period} change={(k,v)=>setPeriod({...period,[k]:v})}/><Actions saving={saving}/></form></Dialog>}</div>
}

function Dialog(p:{title:string;close:()=>void;error:string;children:React.ReactNode}){return <div className="dialog-backdrop"><section className="role-dialog" role="dialog" aria-modal="true"><div className="dialog-heading"><h3>{p.title}</h3><button onClick={p.close}>×</button></div>{p.error&&<p className="content-error" role="alert">{p.error}</p>}{p.children}</section></div>}
function Dates({value,change}:{value:{startsOn:string;endsOn:string};change:(k:'startsOn'|'endsOn',v:string)=>void}){return <div className="form-columns"><label>Начало<input type="date" required value={value.startsOn} onChange={e=>change('startsOn',e.target.value)}/></label><label>Окончание<input type="date" required value={value.endsOn} onChange={e=>change('endsOn',e.target.value)}/></label></div>}
function Actions({saving}:{saving:boolean}){return <div className="dialog-actions"><button className="primary-action" disabled={saving}>{saving?'Сохраняем…':'Сохранить'}</button></div>}