import{FormEvent,useEffect,useState}from'react'
import{AcademicYear,listAcademicYears}from'./academicYears'
import{ClassDraft,ClassRecord,createClass,listClasses}from'./classes'
export default function AdminClassesView(){const[years,setYears]=useState<AcademicYear[]>([]);const[yearID,setYearID]=useState('');const[items,setItems]=useState<ClassRecord[]>([]);const[draft,setDraft]=useState<ClassDraft|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('')
 useEffect(()=>{let active=true;listAcademicYears().then(value=>{if(active){setYears(value);setYearID(value[0]?.id??'')}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Не удалось загрузить учебные годы')});return()=>{active=false}},[])
 useEffect(()=>{if(!yearID){setItems([]);setLoading(false);return}let active=true;setLoading(true);listClasses(yearID).then(value=>{if(active)setItems(value)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Не удалось загрузить классы')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[yearID])
 async function submit(event:FormEvent){event.preventDefault();if(!draft)return;setSaving(true);setError('');try{const saved=await createClass(draft);setItems(current=>[...current,saved]);setDraft(null)}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось создать класс')}finally{setSaving(false)}}
 return <div className="content-stack"><div className="content-heading"><div><p className="content-kicker">Учебный год</p><h2>Классы</h2></div><button className="primary-action" type="button" disabled={!yearID} onClick={()=>setDraft({academicYearId:yearID,name:'',gradeLevel:1})}>+ Создать класс</button></div>
 <label>Учебный год <select aria-label="Учебный год" value={yearID} onChange={event=>setYearID(event.target.value)}>{years.map(year=><option key={year.id} value={year.id}>{year.name}</option>)}</select></label>{error&&<p className="content-error" role="alert">{error}</p>}{loading?<div className="empty-card">Загружаем классы…</div>:<div className="table-card table-scroll"><table className="classes-table"><thead><tr><th>Класс</th><th>Параллель</th><th>Учеников</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.gradeLevel}</td><td>{item.studentCount}</td></tr>)}{!items.length&&<tr><td className="empty-cell" colSpan={3}>Классы ещё не созданы</td></tr>}</tbody></table></div>}
 {draft&&<div className="dialog-backdrop" role="presentation"><section className="role-dialog" role="dialog" aria-modal="true" aria-labelledby="class-dialog-title"><div className="dialog-heading"><h3 id="class-dialog-title">Новый класс</h3><button type="button" aria-label="Закрыть" onClick={()=>setDraft(null)}>×</button></div><form className="role-form" onSubmit={submit}><label>Название<input value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})} required maxLength={100}/></label><label>Параллель<input type="number" min={1} max={11} value={draft.gradeLevel} onChange={event=>setDraft({...draft,gradeLevel:Number(event.target.value)})} required/></label><div className="dialog-actions"><button className="secondary-action" type="button" onClick={()=>setDraft(null)}>Отмена</button><button className="primary-action" type="submit" disabled={saving}>{saving?'Сохраняем…':'Сохранить'}</button></div></form></section></div>}
 </div>}
