import{FormEvent,useEffect,useMemo,useState}from'react'
import{ClassRecord}from'./classes'
import{ClassSubjectRecord,assignSubjectToClass,listClassSubjects,updateClassSubject}from'./classSubjects'
import{Subject as SubjectRecord,listSubjects}from'./subjects'
import{UserRecord,listUsers}from'./users'
import TeacherLessonsView from'./TeacherLessonsView'

export default function ClassSubjectsView({item}:{item:ClassRecord}){
 const[journal,setJournal]=useState<ClassSubjectRecord|null>(null),[assignments,setAssignments]=useState<ClassSubjectRecord[]>([]),[subjects,setSubjects]=useState<SubjectRecord[]>([]),[users,setUsers]=useState<UserRecord[]>([]),[subjectID,setSubjectID]=useState(''),[teacherID,setTeacherID]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let active=true;Promise.all([listClassSubjects(item.id),listSubjects(),listUsers()]).then(([links,catalog,people])=>{if(active){setAssignments(links);setSubjects(catalog);setUsers(people)}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Не удалось загрузить предметы класса')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[item.id])
 const teachers=useMemo(()=>users.filter(user=>user.roles.includes('teacher')),[users]),available=useMemo(()=>subjects.filter(subject=>!assignments.some(link=>link.subject.id===subject.id)),[subjects,assignments])
 if(journal)return <TeacherLessonsView assignment={journal} quarters={item.quarters??[]}/>
 async function assign(event:FormEvent){event.preventDefault();if(!subjectID||!teacherID)return;setSaving(true);setError('');try{const saved=await assignSubjectToClass(item.id,subjectID,teacherID);setAssignments(current=>[...current,saved]);setSubjectID('')}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось назначить предмет')}finally{setSaving(false)}}
 async function replace(assignmentID:string,nextTeacherID:string){setSaving(true);setError('');try{const saved=await updateClassSubject(assignmentID,nextTeacherID);setAssignments(current=>current.map(item=>item.id===assignmentID?saved:item))}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось заменить учителя')}finally{setSaving(false)}}
 return <div className="content-stack">{error&&<p className="content-error" role="alert">{error}</p>}
 <form className="subject-assignment" onSubmit={assign}><label>Предмет<select aria-label="Предмет для класса" value={subjectID} onChange={event=>setSubjectID(event.target.value)} required><option value="">Выберите предмет</option>{available.map(subject=><option key={subject.id} value={subject.id}>{subject.name}</option>)}</select></label><label>Ответственный учитель<select aria-label="Ответственный учитель" value={teacherID} onChange={event=>setTeacherID(event.target.value)} required><option value="">Выберите учителя</option>{teachers.map(teacher=><option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select></label><button className="primary-action" disabled={saving||!subjectID||!teacherID}>Назначить</button></form>
 {loading?<div className="empty-card">Загружаем назначения…</div>:<div className="table-card table-scroll"><table className="subjects-table"><thead><tr><th>Предмет</th><th>Код</th><th>Ответственный учитель</th></tr></thead><tbody>{assignments.map(link=><tr key={link.id}><td><button className="subject-link" onClick={()=>setJournal(link)}>{link.subject.name}</button></td><td>{link.subject.code}</td><td><select aria-label={`Учитель по предмету ${link.subject.name}`} value={link.responsibleTeacher.id} disabled={saving} onChange={event=>replace(link.id,event.target.value)}>{teachers.map(teacher=><option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select></td></tr>)}{!assignments.length&&<tr><td className="empty-cell" colSpan={3}>Предметы классу ещё не назначены</td></tr>}</tbody></table></div>}</div>
}
