import{FormEvent,useEffect,useMemo,useState}from'react'
import{AcademicYear}from'./academicYears'
import{ClassRecord,ClassStudent,addStudentToClass,listClassStudents,updateClassStudent}from'./classes'
import{UserRecord,listUsers}from'./users'
import ClassSubjectsView from'./ClassSubjectsView'

interface Props{item:ClassRecord;year?:AcademicYear;onBack:()=>void;onCountChange:(count:number)=>void}
const today=()=>new Date().toISOString().slice(0,10)

export default function ClassRosterView({item,year,onBack,onCountChange}:Props){
 const[students,setStudents]=useState<ClassStudent[]>([]),[users,setUsers]=useState<UserRecord[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[candidateID,setCandidateID]=useState(''),[enrolledOn,setEnrolledOn]=useState(year?.startsOn??today()),[leftDates,setLeftDates]=useState<Record<string,string>>({})
 const[showSubjects,setShowSubjects]=useState(false)
 useEffect(()=>{let active=true;setLoading(true);Promise.all([listClassStudents(item.id),listUsers()]).then(([members,people])=>{if(active){setStudents(members);setUsers(people)}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Не удалось загрузить состав')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[item.id])
 const candidates=useMemo(()=>{const memberIDs=new Set(students.map(value=>value.student.id)),needle=query.trim().toLowerCase();return users.filter(user=>user.roles.includes('student')&&!memberIDs.has(user.id)&&(`${user.lastName} ${user.firstName}`.toLowerCase().includes(needle)||(user.email??'').toLowerCase().includes(needle)))},[users,students,query])
 async function enroll(event:FormEvent){event.preventDefault();if(!candidateID)return;setSaving(true);setError('');try{const value=await addStudentToClass(item.id,candidateID,enrolledOn);const next=[...students,value];setStudents(next);setCandidateID('');onCountChange(next.filter(student=>!student.leftOn).length)}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось зачислить ученика')}finally{setSaving(false)}}
 async function leave(studentID:string){const date=leftDates[studentID]??today();setSaving(true);setError('');try{const value=await updateClassStudent(item.id,studentID,date);const next=students.map(student=>student.student.id===studentID?value:student);setStudents(next);onCountChange(next.filter(student=>!student.leftOn).length)}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось оформить выбытие')}finally{setSaving(false)}}
 async function restore(studentID:string){setSaving(true);setError('');try{const value=await updateClassStudent(item.id,studentID,null);const next=students.map(student=>student.student.id===studentID?value:student);setStudents(next);onCountChange(next.filter(student=>!student.leftOn).length)}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось отменить выбытие')}finally{setSaving(false)}}
 if(showSubjects)return <ClassSubjectsView item={item} onBack={()=>setShowSubjects(false)}/>
 return <div className="content-stack"><button className="back-button" type="button" onClick={onBack}>← К списку классов</button><div className="content-heading"><div><p className="content-kicker">{year?.name??'Учебный год'}</p><h2>Состав класса {item.name}</h2></div><div className="heading-actions"><button className="secondary-action" type="button" onClick={()=>setShowSubjects(true)}>Предметы класса</button><span className="count-badge">{students.filter(student=>!student.leftOn).length} активных</span></div></div>
 {error&&<p className="content-error" role="alert">{error}</p>}
 <form className="roster-enroll" onSubmit={enroll}><label>Поиск ученика<input aria-label="Поиск ученика" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Фамилия, имя или email"/></label><label>Кандидат<select aria-label="Кандидат" value={candidateID} onChange={event=>setCandidateID(event.target.value)} required><option value="">Выберите ученика</option>{candidates.map(user=><option key={user.id} value={user.id}>{user.lastName} {user.firstName}</option>)}</select></label><label>Дата зачисления<input aria-label="Дата зачисления" type="date" min={year?.startsOn} max={year?.endsOn} value={enrolledOn} onChange={event=>setEnrolledOn(event.target.value)} required/></label><button className="primary-action" disabled={saving||!candidateID}>Зачислить</button></form>
 {loading?<div className="empty-card">Загружаем состав…</div>:<div className="table-card table-scroll"><table className="classes-table roster-table"><thead><tr><th>Ученик</th><th>Зачислен</th><th>Выбыл</th><th>Действие</th></tr></thead><tbody>{students.map(value=><tr key={value.student.id}><td><strong>{value.student.lastName} {value.student.firstName}</strong></td><td>{value.enrolledOn}</td><td>{value.leftOn??'Учится'}</td><td>{value.leftOn?<button className="secondary-action" disabled={saving} onClick={()=>restore(value.student.id)}>Отменить выбытие</button>:<div className="leave-controls"><input aria-label={`Дата выбытия ${value.student.lastName}`} type="date" min={value.enrolledOn} max={year?.endsOn} value={leftDates[value.student.id]??today()} onChange={event=>setLeftDates(current=>({...current,[value.student.id]:event.target.value}))}/><button className="secondary-action" disabled={saving} onClick={()=>leave(value.student.id)}>Оформить выбытие</button></div>}</td></tr>)}{!students.length&&<tr><td className="empty-cell" colSpan={4}>В классе пока нет учеников</td></tr>}</tbody></table></div>}</div>
}
