/* eslint-disable prefer-const */
import{afterEach,expect,it,vi}from'vitest'
import{cleanup,render,screen}from'@testing-library/react'
import userEvent from'@testing-library/user-event'
import AdminClassesView from'./AdminClassesView'
import TeacherLessonsView from'./TeacherLessonsView'
import ParentJournalView from'./ParentJournalView'

function response(value:unknown,status=200){return Promise.resolve(new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}}))}
function mockApi(handler:(url:string,method:string,body:Record<string,unknown>)=>unknown){return vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{const url=String(input),method=init?.method??'GET',body=init?.body?JSON.parse(String(init.body)):{};return response(handler(url,method,body))})}
afterEach(()=>{cleanup();vi.restoreAllMocks()})

it('completes administrator class setup',async()=>{const year={id:'y-1',name:'2026/2027',startsOn:'2026-09-01',endsOn:'2027-05-31',status:'active',quarters:[]},student={id:'s-1',email:'s@test',name:'Анна'+' '+'Иванова',status:'active',roles:['student']},teacher={id:'t-1',email:'t@test',name:'Иван'+' '+'Петров',status:'active',roles:['teacher']},subject={id:'sub-1',code:'math',name:'Математика'};let klass:Record<string,unknown>|null=null,roster:unknown[]=[],assignments:unknown[]=[];mockApi((url,method,body)=>{if(url==='/api/v1/academic-years')return{items:[year]};if(url.startsWith('/api/v1/classes?'))return{items:klass?[klass]:[]};if(url==='/api/v1/classes'&&method==='POST'){klass={id:'c-1',academicYearId:'y-1',name:body.name,gradeLevel:body.gradeLevel,studentCount:0};return{class:klass}};if(url==='/api/v1/classes/c-1/students'&&method==='GET')return{items:roster};if(url==='/api/v1/users?limit=100&offset=0')return{items:[student,teacher]};if(url==='/api/v1/classes/c-1/students'&&method==='POST'){const item={student,enrolledOn:body.enrolledOn,leftOn:null};roster=[item];return{classStudent:item}};if(url==='/api/v1/classes/c-1/subjects'&&method==='GET')return{items:assignments};if(url==='/api/v1/subjects')return{items:[subject]};if(url==='/api/v1/classes/c-1/subjects'&&method==='POST'){const item={id:'cs-1',classId:'c-1',subject,responsibleTeacher:teacher};assignments=[item];return{classSubject:item}};throw new Error(`${method} ${url}`)});render(<AdminClassesView/>);await userEvent.click(await screen.findByRole('button',{name:/Создать класс/}));await userEvent.type(screen.getByLabelText('Название'),'7А');await userEvent.clear(screen.getByLabelText('Параллель'));await userEvent.type(screen.getByLabelText('Параллель'),'7');await userEvent.click(screen.getByRole('button',{name:'Сохранить'}));await userEvent.click(await screen.findByRole('button',{name:'7А'}));await userEvent.click(await screen.findByRole('button',{name:'+ Добавить ученика'}));await userEvent.selectOptions(await screen.findByLabelText('Кандидат'),'s-1');await userEvent.click(screen.getByRole('button',{name:'Зачислить'}));await userEvent.click(screen.getByRole('button',{name:'Предметы класса'}));await userEvent.selectOptions(await screen.findByLabelText('Предмет для класса'),'sub-1');await userEvent.selectOptions(screen.getByLabelText('Ответственный учитель'),'t-1');await userEvent.click(screen.getByRole('button',{name:'Назначить'}));expect(await screen.findByText('Математика')).toBeInTheDocument()})

it('completes teacher journal entry',async()=>{const assignment={id:'cs-1',classId:'c-1',subject:{id:'sub-1',code:'math',name:'Математика'},responsibleTeacher:{id:'t-1',name:'Иван'+' '+'Петров',roles:['teacher']}},student={student:{id:'s-1',name:'Анна'+' '+'Иванова',roles:['student']},enrolledOn:'2026-09-01',leftOn:null};let lessons:Record<string,unknown>[]=[],grades:unknown[]=[];mockApi((url,method,body)=>{if(url.startsWith('/api/v1/class-subjects/cs-1/lessons?'))return{items:lessons};if(url==='/api/v1/classes/c-1/students')return{items:[student]};if(url.includes('/quarters/q-1/grades')&&method==='GET')return{items:grades};if(url==='/api/v1/class-subjects/cs-1/lessons'&&method==='POST'){const lesson={id:'l-1',classSubjectId:'cs-1',lessonDate:body.lessonDate,position:1,topic:body.topic,homework:null,materials:[],gradeItems:[],absences:[]};lessons=[lesson];return{lesson}};if(url==='/api/v1/lessons/l-1/grade-items'){const item={id:'g-1',lessonId:'l-1',title:body.title,kind:'classwork',gradingScale:'five_point',scores:[]};return{gradeItem:item}};if(url==='/api/v1/grade-items/g-1/scores/s-1')return{score:{id:'score-1',gradeItemId:'g-1',studentId:'s-1',numericValue:5,teacherComment:'Отлично'}};throw new Error(`${method} ${url}`)});render(<TeacherLessonsView assignment={assignment} quarters={[{id:'q-1',number:1,startsOn:'2026-09-09',endsOn:'2026-09-09'}]}/>);await userEvent.click(await screen.findByRole('button',{name:'Домашнее задание 2026-09-09'}));await userEvent.type(screen.getByLabelText('Тема'),'Дроби');await userEvent.click(screen.getByRole('button',{name:'Сохранить'}));await userEvent.click(await screen.findByRole('button',{name:'Добавить Работа на уроке'}));await userEvent.type(screen.getByLabelText('Оценка Работа на уроке'),'5');await userEvent.type(screen.getByLabelText('Комментарий Работа на уроке'),'Отлично');await userEvent.click(screen.getByRole('button',{name:'Сохранить оценку'}));expect(await screen.findByText('5*')).toBeInTheDocument()})

it('completes parent report viewing',async()=>{const student={id:'s-1',name:'Анна'+' '+'Иванова',roles:['student']},subject={id:'cs-1',classId:'c-1',subject:{id:'sub-1',code:'math',name:'Математика'},responsibleTeacher:{id:'t-1',name:'Иван'+' '+'Петров',roles:['teacher']}},year={id:'y-1',name:'2026/2027',startsOn:'2026-09-01',endsOn:'2027-05-31',status:'active',quarters:[{id:'q-1',number:1,name:'Осень',startsOn:'2026-09-01',endsOn:'2026-10-31'}]},klass={id:'c-1',academicYearId:'y-1',name:'7А',gradeLevel:7,studentCount:1},lesson={id:'l-1',classSubjectId:'cs-1',lessonDate:'2026-09-09',position:1,topic:'Дроби',homework:'№ 5',materials:[],absences:[],gradeItems:[{id:'g-1',lessonId:'l-1',title:'Работа',kind:'classwork',gradingScale:'five_point',scores:[{id:'sc-1',gradeItemId:'g-1',studentId:'s-1',numericValue:5,teacherComment:'Отлично'}]}]};mockApi(url=>{if(url==='/api/v1/parent/students')return{items:[student]};if(url.endsWith('/periods'))return{items:[{academicYear:year,class:klass,subjects:[subject]}]};if(url.includes('/journal?'))return{student,academicYear:year,class:klass,subjects:[{classSubject:subject,lessons:[{lesson}],quarterGrades:[{id:'qg-1',quarterId:'q-1',classSubjectId:'cs-1',studentId:'s-1',gradingScale:'five_point',numericValue:5}]}]};throw new Error(url)});render(<ParentJournalView/>);await userEvent.click(await screen.findByRole('button',{name:'Анна Иванова'}));await userEvent.click(await screen.findByRole('button',{name:'7А'}));await userEvent.click(await screen.findByRole('button',{name:'Математика'}));expect(await screen.findByText('Отлично')).toBeInTheDocument();expect(screen.getByText(/Осень/)).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Сохранить/})).not.toBeInTheDocument()})
