import{useEffect,useState}from'react'
import{ClassSubjectRecord}from'./classSubjects'
import{ParentStudent,ParentStudentPeriod,listCurrentParentStudents,listParentStudentPeriods}from'./parentJournal'

export default function ParentJournalView(){const[students,setStudents]=useState<ParentStudent[]>([]),[student,setStudent]=useState<ParentStudent|null>(null),[periods,setPeriods]=useState<ParentStudentPeriod[]>([]),[period,setPeriod]=useState<ParentStudentPeriod|null>(null),[subject,setSubject]=useState<ClassSubjectRecord|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{listCurrentParentStudents().then(setStudents).catch(cause=>setError(cause instanceof Error?cause.message:'Не удалось загрузить детей')).finally(()=>setLoading(false))},[]);async function openStudent(value:ParentStudent){setStudent(value);setPeriod(null);setSubject(null);setLoading(true);setError('');try{setPeriods(await listParentStudentPeriods(value.id))}catch(cause){setPeriods([]);setError(cause instanceof Error?cause.message:'Доступ к журналу отозван')}finally{setLoading(false)}}
 if(subject&&period&&student)return <div className="content-stack"><button className="back-button" onClick={()=>setSubject(null)}>← К предметам</button><p className="content-kicker">{student.lastName} {student.firstName} · {period.class.name}</p><h2>{subject.subject.name}</h2><div className="empty-card">Табель по предмету будет показан здесь.</div></div>
 if(period&&student)return <div className="content-stack"><button className="back-button" onClick={()=>setPeriod(null)}>← К учебным периодам</button><div className="content-heading"><div><p className="content-kicker">{student.lastName} {student.firstName}</p><h2>{period.class.name} · {period.academicYear.name}</h2></div></div><div className="table-card"><table className="subjects-table"><thead><tr><th>Предмет</th><th>Учитель</th></tr></thead><tbody>{period.subjects.map(item=><tr key={item.id}><td><button className="subject-link" onClick={()=>setSubject(item)}>{item.subject.name}</button></td><td>{item.responsibleTeacher.lastName} {item.responsibleTeacher.firstName}</td></tr>)}{!period.subjects.length&&<tr><td className="empty-cell" colSpan={2}>В классе пока нет предметов</td></tr>}</tbody></table></div></div>
 if(student)return <div className="content-stack"><button className="back-button" onClick={()=>setStudent(null)}>← К детям</button><div className="content-heading"><div><p className="content-kicker">История обучения</p><h2>{student.lastName} {student.firstName}</h2></div></div>{error&&<p className="content-error" role="alert">{error}</p>}{loading?<div className="empty-card">Загружаем историю…</div>:periods.length?<div className="table-card"><table className="classes-table"><thead><tr><th>Учебный год</th><th>Класс</th><th>Предметов</th></tr></thead><tbody>{periods.map(item=><tr key={`${item.academicYear.id}-${item.class.id}`}><td>{item.academicYear.name}</td><td><button className="class-link" onClick={()=>setPeriod(item)}>{item.class.name}</button></td><td>{item.subjects.length}</td></tr>)}</tbody></table></div>:<div className="empty-card">История обучения пока пуста</div>}</div>
 return <div className="content-stack"><div className="content-heading"><div><p className="content-kicker">Родительский кабинет</p><h2>Мои дети</h2></div><span className="count-badge">{students.length}</span></div>{error&&<p className="content-error" role="alert">{error}</p>}{loading?<div className="empty-card">Загружаем детей…</div>:students.length?<div className="table-card"><table className="classes-table"><thead><tr><th>Ребёнок</th></tr></thead><tbody>{students.map(item=><tr key={item.id}><td><button className="subject-link" onClick={()=>void openStudent(item)}>{item.lastName} {item.firstName}</button></td></tr>)}</tbody></table></div>:<div className="empty-card">Нет доступных детей</div>}</div>}
