import{useEffect,useState}from'react'
import{ClassSubjectRecord}from'./classSubjects'
import{ParentJournalSubject,ParentStudent,ParentStudentPeriod,getParentStudentJournal,listCurrentParentStudents,listParentStudentPeriods}from'./parentJournal'

export default function ParentJournalView(){const[students,setStudents]=useState<ParentStudent[]>([]),[student,setStudent]=useState<ParentStudent|null>(null),[periods,setPeriods]=useState<ParentStudentPeriod[]>([]),[period,setPeriod]=useState<ParentStudentPeriod|null>(null),[subject,setSubject]=useState<ClassSubjectRecord|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{listCurrentParentStudents().then(setStudents).catch(cause=>setError(cause instanceof Error?cause.message:'Не удалось загрузить детей')).finally(()=>setLoading(false))},[]);async function openStudent(value:ParentStudent){setStudent(value);setPeriod(null);setSubject(null);setLoading(true);setError('');try{setPeriods(await listParentStudentPeriods(value.id))}catch(cause){setPeriods([]);setError(cause instanceof Error?cause.message:'Доступ к журналу отозван')}finally{setLoading(false)}}
 if(subject&&period&&student)return <ParentSubjectJournal student={student} period={period} subject={subject} onBack={()=>setSubject(null)}/>
 if(period&&student)return <div className="content-stack"><button className="back-button" onClick={()=>setPeriod(null)}>← К учебным периодам</button><div className="content-heading"><div><p className="content-kicker">{student.name}</p><h2>{period.class.name} · {period.academicYear.name}</h2></div></div><div className="table-card"><table className="subjects-table"><thead><tr><th>Предмет</th><th>Учитель</th></tr></thead><tbody>{period.subjects.map(item=><tr key={item.id}><td><button className="subject-link" onClick={()=>setSubject(item)}>{item.subject.name}</button></td><td>{item.responsibleTeacher.name}</td></tr>)}{!period.subjects.length&&<tr><td className="empty-cell" colSpan={2}>В классе пока нет предметов</td></tr>}</tbody></table></div></div>
 if(student)return <div className="content-stack"><button className="back-button" onClick={()=>setStudent(null)}>← К детям</button><div className="content-heading"><div><p className="content-kicker">История обучения</p><h2>{student.name}</h2></div></div>{error&&<p className="content-error" role="alert">{error}</p>}{loading?<div className="empty-card">Загружаем историю…</div>:periods.length?<div className="table-card"><table className="classes-table"><thead><tr><th>Учебный год</th><th>Класс</th><th>Предметов</th></tr></thead><tbody>{periods.map(item=><tr key={`${item.academicYear.id}-${item.class.id}`}><td>{item.academicYear.name}</td><td><button className="class-link" onClick={()=>setPeriod(item)}>{item.class.name}</button></td><td>{item.subjects.length}</td></tr>)}</tbody></table></div>:<div className="empty-card">История обучения пока пуста</div>}</div>
 return <div className="content-stack"><div className="content-heading"><div><p className="content-kicker">Родительский кабинет</p><h2>Мои дети</h2></div><span className="count-badge">{students.length}</span></div>{error&&<p className="content-error" role="alert">{error}</p>}{loading?<div className="empty-card">Загружаем детей…</div>:students.length?<div className="table-card"><table className="classes-table"><thead><tr><th>Ребёнок</th></tr></thead><tbody>{students.map(item=><tr key={item.id}><td><button className="subject-link" onClick={()=>void openStudent(item)}>{item.name}</button></td></tr>)}</tbody></table></div>:<div className="empty-card">Нет доступных детей</div>}</div>}

function ParentSubjectJournal({student,period,subject,onBack}:{student:ParentStudent;period:ParentStudentPeriod;subject:ClassSubjectRecord;onBack:()=>void}){const[data,setData]=useState<ParentJournalSubject|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{getParentStudentJournal(student.id,period.academicYear.id).then(journal=>setData(journal.subjects.find(item=>item.classSubject.id===subject.id)??null)).catch(cause=>setError(cause instanceof Error?cause.message:'Не удалось загрузить табель')).finally(()=>setLoading(false))},[student.id,period.academicYear.id,subject.id]);return <div className="content-stack"><button className="back-button" onClick={onBack}>← К предметам</button><div><p className="content-kicker">{student.name} · {period.class.name}</p><h2>{subject.subject.name}</h2></div>{error&&<p className="content-error" role="alert">{error}</p>}{loading?<div className="empty-card">Загружаем табель…</div>:<>{data?.quarterGrades?.length?<div className="quarter-summary">{data.quarterGrades.map(item=><span key={item.id}>{period.academicYear.quarters.find(q=>q.id===item.quarterId)?.name??'Период'}: <strong>{item.numericValue??(item.textValue==='pass'?'Зачёт':'Незачёт')}</strong></span>)}</div>:null}{data?.lessons.length?<div className="table-card table-scroll"><table className="parent-journal"><thead><tr><th>Дата и тема</th><th>Домашнее задание</th><th>Материалы</th><th>Работы и оценки</th><th>Посещение</th></tr></thead><tbody>{data.lessons.map(({lesson})=><tr key={lesson.id}><td><strong>{lesson.lessonDate}</strong><span>{lesson.topic}</span></td><td>{lesson.homework??'—'}</td><td>{lesson.materials.length?lesson.materials.map(item=><a href={item.url} key={item.id}>{item.title}</a>):'—'}</td><td>{lesson.gradeItems.length?lesson.gradeItems.map(item=>{const score=item.scores[0];return <div className="parent-score" key={item.id}><strong>{item.title}: {score?score.numericValue??(score.textValue==='pass'?'Зачёт':'Незачёт'):'—'}</strong>{score?.teacherComment&&<span>{score.teacherComment}</span>}</div>}):'—'}</td><td>{lesson.absences.length?<span className="absence-mark">Пропуск</span>:'Был'}</td></tr>)}</tbody></table></div>:<div className="empty-card">По предмету пока нет уроков</div>}</>}</div>}
