import{FormEvent,useEffect,useMemo,useState}from'react'
import{UserRecord,grantParentStudent,listParentStudents,listUsers,revokeParentStudent}from'./users'

export default function ParentChildrenView({parent,onBack}:{parent:UserRecord;onBack:()=>void}){
 const[children,setChildren]=useState<UserRecord[]>([]),[users,setUsers]=useState<UserRecord[]>([]),[candidateID,setCandidateID]=useState(''),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let active=true;Promise.all([listParentStudents(parent.id),listUsers()]).then(([linked,all])=>{if(active){setChildren(linked);setUsers(all)}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Не удалось загрузить детей')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[parent.id])
 const candidates=useMemo(()=>{const linked=new Set(children.map(child=>child.id)),needle=query.trim().toLowerCase();return users.filter(user=>user.roles.includes('student')&&!linked.has(user.id)&&`${user.lastName} ${user.firstName} ${user.email}`.toLowerCase().includes(needle))},[children,users,query])
 async function add(event:FormEvent){event.preventDefault();const student=users.find(user=>user.id===candidateID);if(!student)return;setSaving(true);setError('');try{await grantParentStudent(parent.id,student.id);setChildren(current=>[...current,student]);setCandidateID('')}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось добавить ребёнка')}finally{setSaving(false)}}
 async function remove(student:UserRecord){setSaving(true);setError('');try{await revokeParentStudent(parent.id,student.id);setChildren(current=>current.filter(item=>item.id!==student.id))}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось отозвать доступ')}finally{setSaving(false)}}
 return <div className="content-stack"><button className="back-button" onClick={onBack}>← К пользователям</button><div className="content-heading"><div><p className="content-kicker">Родитель {parent.firstName} {parent.lastName}</p><h2>Доступ к детям</h2></div><span className="count-badge">{children.length}</span></div>{error&&<p className="content-error" role="alert">{error}</p>}<form className="subject-assignment" onSubmit={add}><label>Поиск ученика<input aria-label="Поиск ученика" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Фамилия, имя или email"/></label><label>Ученик<select aria-label="Ученик для родителя" value={candidateID} onChange={event=>setCandidateID(event.target.value)} required><option value="">Выберите ученика</option>{candidates.map(user=><option key={user.id} value={user.id}>{user.lastName} {user.firstName}</option>)}</select></label><button className="primary-action" disabled={saving||!candidateID}>Добавить</button></form>{loading?<div className="empty-card">Загружаем детей…</div>:<div className="table-card"><table className="roles-table"><thead><tr><th>Ученик</th><th>Email</th><th>Действие</th></tr></thead><tbody>{children.map(child=><tr key={child.id}><td><strong>{child.lastName} {child.firstName}</strong></td><td>{child.email??'—'}</td><td><button className="danger-action secondary-action" disabled={saving} onClick={()=>remove(child)}>Отозвать доступ</button></td></tr>)}{!children.length&&<tr><td className="empty-cell" colSpan={3}>Дети ещё не добавлены</td></tr>}</tbody></table></div>}</div>
}
