import{FormEvent,useEffect,useState}from'react'
import{createSubject,listSubjects,Subject,SubjectDraft}from'./subjects'
const empty:SubjectDraft={code:'',name:''}
export default function SubjectsView(){
 const[items,setItems]=useState<Subject[]>([]);const[draft,setDraft]=useState<SubjectDraft|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('')
 useEffect(()=>{let active=true;listSubjects().then(value=>{if(active)setItems(value)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Не удалось загрузить предметы')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 async function submit(event:FormEvent){event.preventDefault();if(!draft)return;setSaving(true);setError('');try{const saved=await createSubject(draft);setItems(current=>[...current,saved].sort((a,b)=>a.name.localeCompare(b.name,'ru')));setDraft(null)}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось создать предмет')}finally{setSaving(false)}}
 return <div className="content-stack"><div className="content-heading"><div><p className="content-kicker">Общий справочник</p><h2>Предметы</h2></div><button className="primary-action" type="button" onClick={()=>setDraft({...empty})}>+ Создать предмет</button></div>
 {error&&<p className="content-error" role="alert">{error}</p>}{loading?<div className="empty-card">Загружаем предметы…</div>:<div className="table-card table-scroll"><table className="roles-table"><thead><tr><th>Название</th><th>Код</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td><code>{item.code}</code></td></tr>)}{!items.length&&<tr><td className="empty-cell" colSpan={2}>Предметы ещё не созданы</td></tr>}</tbody></table></div>}
 {draft&&<div className="dialog-backdrop" role="presentation"><section className="role-dialog" role="dialog" aria-modal="true" aria-labelledby="subject-dialog-title"><div className="dialog-heading"><h3 id="subject-dialog-title">Новый предмет</h3><button type="button" aria-label="Закрыть" onClick={()=>setDraft(null)}>×</button></div><form className="role-form" onSubmit={submit}><label>Название<input value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})} required maxLength={100}/></label><label>Код<input value={draft.code} onChange={event=>setDraft({...draft,code:event.target.value})} required pattern="[a-z][a-z0-9_]*"/></label><div className="dialog-actions"><button className="secondary-action" type="button" onClick={()=>setDraft(null)}>Отмена</button><button className="primary-action" type="submit" disabled={saving}>{saving?'Сохраняем…':'Сохранить'}</button></div></form></section></div>}
 </div>
}
