import{FormEvent,useCallback,useEffect,useMemo,useState}from'react'
import{ClassStudent,listClassStudents}from'./classes'
import{ClassSubjectRecord}from'./classSubjects'
import{GradeItem,GradeItemDraft,LessonDraft,LessonRecord,Score,createGradeItem,createLesson,listLessons,putStudentScore}from'./lessons'

const emptyLesson=():LessonDraft=>({lessonDate:new Date().toISOString().slice(0,10),position:1,topic:'',homework:'',materials:[]})
export default function TeacherLessonsView({assignment,onBack}:{assignment:ClassSubjectRecord;onBack:()=>void}){
 const[items,setItems]=useState<LessonRecord[]>([]),[students,setStudents]=useState<ClassStudent[]>([]),[from,setFrom]=useState(''),[to,setTo]=useState(''),[draft,setDraft]=useState<LessonDraft|null>(null),[gradeLessonID,setGradeLessonID]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');try{const[lessons,roster]=await Promise.all([listLessons(assignment.id,from,to),listClassStudents(assignment.classId)]);setItems(lessons);setStudents(roster)}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось загрузить журнал')}finally{setLoading(false)}},[assignment.id,assignment.classId,from,to])
 useEffect(()=>{void load()},[load])
 async function submit(event:FormEvent){event.preventDefault();if(!draft)return;setSaving(true);try{const saved=await createLesson(assignment.id,{...draft,homework:draft.homework||undefined});setItems(current=>[...current,saved]);setDraft(null)}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось создать урок')}finally{setSaving(false)}}
 function scoreSaved(saved:Score){setItems(current=>current.map(lesson=>({...lesson,gradeItems:lesson.gradeItems.map(item=>item.id!==saved.gradeItemId?item:{...item,scores:[...item.scores.filter(score=>score.studentId!==saved.studentId),saved]})})))}
 if(gradeLessonID)return <GradeEditor lessonID={gradeLessonID} onBack={()=>setGradeLessonID('')} onSaved={saved=>setItems(current=>current.map(item=>item.id===gradeLessonID?{...item,gradeItems:[...item.gradeItems,saved]}:item))}/>
 return <div className="content-stack"><button className="back-button" onClick={onBack}>← Мои предметы</button><div className="content-heading"><div><p className="content-kicker">{assignment.subject.name}</p><h2>Журнал класса</h2></div><button className="primary-action" onClick={()=>setDraft(emptyLesson())}>+ Создать урок</button></div><div className="lesson-filters"><label>С даты<input aria-label="С даты" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>По дату<input aria-label="По дату" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>{error&&<p className="content-error" role="alert">{error}</p>}{loading?<div className="empty-card">Загружаем журнал…</div>:<><LessonList items={items} onAddGrade={setGradeLessonID}/><GradeTable items={items} students={students} onSaved={scoreSaved}/></>}{draft&&<LessonDialog draft={draft} setDraft={setDraft} saving={saving} submit={submit}/>}</div>
}

function LessonList({items,onAddGrade}:{items:LessonRecord[];onAddGrade:(id:string)=>void}){return <div className="table-card"><table className="subjects-table"><thead><tr><th>Дата</th><th>№</th><th>Тема</th><th>Задание</th><th>Работы</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td>{item.lessonDate}</td><td>{item.position}</td><td><strong>{item.topic}</strong>{item.materials.map(material=><a key={material.id} href={material.url}>{material.title}</a>)}</td><td>{item.homework??'—'}</td><td>{item.gradeItems.map(grade=><span className="status-badge" key={grade.id}>{grade.title}</span>)}<button className="secondary-action" onClick={()=>onAddGrade(item.id)}>+ Работа</button></td></tr>)}{!items.length&&<tr><td className="empty-cell" colSpan={5}>Уроки ещё не созданы</td></tr>}</tbody></table></div>}

function GradeTable({items,students,onSaved}:{items:LessonRecord[];students:ClassStudent[];onSaved:(score:Score)=>void}){
 const columns=useMemo(()=>items.flatMap(lesson=>lesson.gradeItems.map(item=>({lesson,item}))),[items])
 if(!columns.length)return <div className="empty-card">Создайте оцениваемую работу, чтобы начать заполнять оценки.</div>
 return <div className="table-card journal-scroll"><table className="journal-table"><thead><tr><th className="student-heading">Ученик</th>{columns.map(({lesson,item})=><th key={item.id}><span className="lesson-date">{lesson.lessonDate}</span>{item.title}<span className="lesson-day">{scaleLabel(item)}</span></th>)}</tr></thead><tbody>{students.map(member=><tr key={member.student.id}><th><span className="student-name">{member.student.lastName} {member.student.firstName}</span></th>{columns.map(({lesson,item})=><td key={item.id}><ScoreEditor item={item} studentID={member.student.id} disabled={lesson.lessonDate<member.enrolledOn||!!member.leftOn&&lesson.lessonDate>member.leftOn} onSaved={onSaved}/></td>)}</tr>)}</tbody></table></div>
}

function ScoreEditor({item,studentID,disabled,onSaved}:{item:GradeItem;studentID:string;disabled:boolean;onSaved:(score:Score)=>void}){
 const existing=item.scores.find(score=>score.studentId===studentID),initial=existing?.numericValue?.toString()??existing?.textValue??''
 const[value,setValue]=useState(initial),[comment,setComment]=useState(existing?.teacherComment??''),[state,setState]=useState<'idle'|'saving'|'saved'|'error'>('idle')
 async function save(){if(!value||disabled)return;setState('saving');try{const payload=item.gradingScale==='pass_fail'?{textValue:value,teacherComment:comment||undefined}:{numericValue:Number(value),teacherComment:comment||undefined};onSaved(await putStudentScore(item.id,studentID,payload));setState('saved')}catch{setState('error')}}
 return <div className="score-editor">{item.gradingScale==='pass_fail'?<select aria-label={`Оценка ${item.title}`} disabled={disabled} value={value} onChange={e=>{setValue(e.target.value);setState('idle')}}><option value="">—</option><option value="pass">Зачёт</option><option value="fail">Незачёт</option></select>:<input aria-label={`Оценка ${item.title}`} disabled={disabled} type="number" min={item.gradingScale==='five_point'?2:0} max={item.gradingScale==='five_point'?5:item.maxScore??undefined} step={item.gradingScale==='five_point'?1:.01} value={value} onChange={e=>{setValue(e.target.value);setState('idle')}}/>}<input aria-label={`Комментарий ${item.title}`} disabled={disabled} placeholder="Комментарий" value={comment} onChange={e=>{setComment(e.target.value);setState('idle')}}/><button className="secondary-action" disabled={disabled||!value||state==='saving'} onClick={save}>{state==='saving'?'…':state==='saved'?'✓':'Сохранить'}</button>{state==='error'&&<small role="alert">Ошибка сохранения</small>}</div>
}

function scaleLabel(item:GradeItem){return item.gradingScale==='five_point'?'2–5':item.gradingScale==='pass_fail'?'зачёт/незачёт':`0–${item.maxScore}`}
function LessonDialog({draft,setDraft,saving,submit}:{draft:LessonDraft;setDraft:(value:LessonDraft|null)=>void;saving:boolean;submit:(event:FormEvent)=>void}){return <div className="dialog-backdrop"><form className="role-dialog role-form" onSubmit={submit}><h3>Новый урок</h3><label>Дата<input aria-label="Дата урока" type="date" value={draft.lessonDate} onChange={e=>setDraft({...draft,lessonDate:e.target.value})}/></label><label>Позиция<input aria-label="Позиция урока" type="number" min="1" value={draft.position} onChange={e=>setDraft({...draft,position:Number(e.target.value)})}/></label><label>Тема<input value={draft.topic} onChange={e=>setDraft({...draft,topic:e.target.value})} required/></label><label>Домашнее задание<input value={draft.homework} onChange={e=>setDraft({...draft,homework:e.target.value})}/></label><button type="button" className="secondary-action" onClick={()=>setDraft({...draft,materials:[...draft.materials,{title:'',url:'',position:draft.materials.length+1}]})}>+ Материал</button>{draft.materials.map((material,i)=><div className="form-columns" key={i}><label>Название материала<input aria-label={`Название материала ${i+1}`} value={material.title} onChange={e=>setDraft({...draft,materials:draft.materials.map((m,j)=>j===i?{...m,title:e.target.value}:m)})}/></label><label>Ссылка<input aria-label={`Ссылка материала ${i+1}`} type="url" value={material.url} onChange={e=>setDraft({...draft,materials:draft.materials.map((m,j)=>j===i?{...m,url:e.target.value}:m)})}/></label></div>)}<button className="primary-action" disabled={saving}>Сохранить</button></form></div>}
function GradeEditor({lessonID,onBack,onSaved}:{lessonID:string;onBack:()=>void;onSaved:(item:GradeItem)=>void}){const[value,setValue]=useState<GradeItemDraft>({title:'',kind:'homework',gradingScale:'five_point'}),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();try{const saved=await createGradeItem(lessonID,value);onSaved(saved);onBack()}catch(cause){setError(cause instanceof Error?cause.message:'Ошибка')}}return <div className="content-stack"><button className="back-button" onClick={onBack}>← К урокам</button><h2>Новая работа</h2>{error&&<p role="alert">{error}</p>}<form className="role-form" onSubmit={submit}><label>Название<input value={value.title} onChange={e=>setValue({...value,title:e.target.value})}/></label><label>Тип<select aria-label="Тип работы" value={value.kind} onChange={e=>setValue({...value,kind:e.target.value as GradeItem['kind']})}><option value="homework">Домашняя</option><option value="classwork">Классная</option><option value="knowledge_check">Проверочная</option><option value="other">Другая</option></select></label><label>Шкала<select aria-label="Шкала" value={value.gradingScale} onChange={e=>{const gradingScale=e.target.value as GradeItem['gradingScale'];setValue({...value,gradingScale,maxScore:undefined})}}><option value="five_point">Пятибалльная</option><option value="points">Баллы</option><option value="pass_fail">Зачёт</option></select></label>{value.gradingScale==='points'&&<label>Максимальный балл<input aria-label="Максимальный балл" type="number" min="0.01" step="0.01" onChange={e=>setValue({...value,maxScore:Number(e.target.value)})}/></label>}<button className="primary-action">Создать работу</button></form></div>}
