import{useEffect,useState}from'react'
import{ClassRecord}from'./classes'
import{ClassSubjectRecord}from'./classSubjects'
import{listTeacherClasses,listTeacherClassSubjects}from'./teacherClasses'

export default function TeacherClassesView(){
 const[classes,setClasses]=useState<ClassRecord[]>([]),[selected,setSelected]=useState<ClassRecord|null>(null),[subjects,setSubjects]=useState<ClassSubjectRecord[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{let active=true;listTeacherClasses().then(items=>{if(active)setClasses(items)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Не удалось загрузить классы')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 async function open(item:ClassRecord){setSelected(item);setLoading(true);setError('');try{setSubjects(await listTeacherClassSubjects(item.id))}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось загрузить предметы')}finally{setLoading(false)}}
 if(selected)return <div className="content-stack"><button className="back-button" onClick={()=>setSelected(null)}>← Мои классы</button><div className="content-heading"><div><p className="content-kicker">Класс {selected.name}</p><h2>Мои предметы</h2></div><span className="count-badge">{subjects.length}</span></div>{error&&<p className="content-error" role="alert">{error}</p>}{loading?<div className="empty-card">Загружаем предметы…</div>:<div className="table-card"><table className="subjects-table"><thead><tr><th>Предмет</th><th>Код</th></tr></thead><tbody>{subjects.map(item=><tr key={item.id}><td><strong>{item.subject.name}</strong></td><td>{item.subject.code}</td></tr>)}{!subjects.length&&<tr><td className="empty-cell" colSpan={2}>Нет доступных предметов</td></tr>}</tbody></table></div>}</div>
 return <div className="content-stack"><div className="content-heading"><div><p className="content-kicker">Кабинет учителя</p><h2>Мои классы</h2></div><span className="count-badge">{classes.length}</span></div>{error&&<p className="content-error" role="alert">{error}</p>}{loading?<div className="empty-card">Загружаем классы…</div>:<div className="table-card"><table className="classes-table"><thead><tr><th>Класс</th><th>Параллель</th><th>Учеников</th></tr></thead><tbody>{classes.map(item=><tr key={item.id}><td><button className="class-link" onClick={()=>open(item)}>{item.name}</button></td><td>{item.gradeLevel}</td><td>{item.studentCount}</td></tr>)}{!classes.length&&<tr><td className="empty-cell" colSpan={3}>Нет доступных классов</td></tr>}</tbody></table></div>}</div>
}
