import{afterEach,expect,it,vi}from'vitest'
import{cleanup,render,screen}from'@testing-library/react'
import userEvent from'@testing-library/user-event'
import TeacherLessonsView from'./TeacherLessonsView'

const assignment={id:'link-1',classId:'class-1',subject:{id:'s-1',code:'MATH',name:'Математика'},responsibleTeacher:{id:'t-1',firstName:'Иван',lastName:'Петров',roles:['teacher']}}
const student={student:{id:'student-1',firstName:'Анна',lastName:'Иванова',roles:['student']},enrolledOn:'2026-09-01',leftOn:null}
afterEach(()=>{cleanup();vi.restoreAllMocks()})
it('creates lesson with a material',async()=>{vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(new Response(JSON.stringify({items:[]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({items:[]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({lesson:{id:'l-1',classSubjectId:'link-1',lessonDate:'2026-09-09',position:1,topic:'Дроби',homework:null,materials:[{id:'m-1',title:'Видео',url:'https://example.test',position:1}],gradeItems:[]}}),{status:201}));render(<TeacherLessonsView assignment={assignment} onBack={()=>{}}/>);await userEvent.click(await screen.findByRole('button',{name:/Создать урок/}));await userEvent.clear(screen.getByLabelText('Дата урока'));await userEvent.type(screen.getByLabelText('Дата урока'),'2026-09-09');await userEvent.type(screen.getByLabelText('Тема'),'Дроби');await userEvent.click(screen.getByRole('button',{name:/Материал/}));await userEvent.type(screen.getByLabelText('Название материала 1'),'Видео');await userEvent.type(screen.getByLabelText('Ссылка материала 1'),'https://example.test');await userEvent.click(screen.getByRole('button',{name:'Сохранить'}));expect(await screen.findByText('Дроби')).toBeInTheDocument()})
it('loads roster and saves a score with comment',async()=>{const lesson={id:'l-1',classSubjectId:'link-1',lessonDate:'2026-09-09',position:1,topic:'Дроби',materials:[],gradeItems:[{id:'g-1',lessonId:'l-1',title:'Самостоятельная',kind:'classwork',gradingScale:'five_point',scores:[]}]};vi.spyOn(globalThis,'fetch').mockResolvedValueOnce(new Response(JSON.stringify({items:[lesson]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({items:[student]}),{status:200})).mockResolvedValueOnce(new Response(JSON.stringify({score:{id:'score-1',gradeItemId:'g-1',studentId:'student-1',numericValue:5,teacherComment:'Отлично'}}),{status:200}));render(<TeacherLessonsView assignment={assignment} onBack={()=>{}}/>);await screen.findByText('Иванова Анна');await userEvent.type(screen.getByLabelText('Оценка Самостоятельная'),'5');await userEvent.type(screen.getByLabelText('Комментарий Самостоятельная'),'Отлично');await userEvent.click(screen.getByRole('button',{name:'Сохранить'}));expect(await screen.findByRole('button',{name:'✓'})).toBeInTheDocument();expect(globalThis.fetch).toHaveBeenLastCalledWith('/api/v1/grade-items/g-1/scores/student-1',expect.objectContaining({method:'PUT'}))})
