import{FormEvent,useEffect,useState}from'react'
import{listRoles,Role}from'./roles'
import{createUser,deleteUser,listUsers,updateUser,UserDraft,UserRecord,UsersApiError}from'./users'
import ParentChildrenView from'./ParentChildrenView'
type Editor=UserDraft&{id?:string}
const empty:Editor={login:'',email:'',phone:'',password:'',name:''+' '+'',status:'active',roles:[]}
export default function UsersView(){
 const[users,setUsers]=useState<UserRecord[]>([]);const[roles,setRoles]=useState<Role[]>([]);const[editor,setEditor]=useState<Editor|null>(null);const[parent,setParent]=useState<UserRecord|null>(null);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState('')
 useEffect(()=>{let active=true;Promise.all([listUsers(),listRoles()]).then(([u,r])=>{if(active){setUsers(u);setRoles(r)}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'Не удалось загрузить пользователей')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
 function open(user?:UserRecord){setError('');setEditor(user?{...user,login:user.login??'',email:user.email??'',phone:user.phone??'',password:'',roles:[...user.roles]}:{...empty,roles:[]})}
 function toggleRole(code:string){setEditor(value=>value?{...value,roles:value.roles.includes(code)?value.roles.filter(item=>item!==code):[...value.roles,code]}:value)}
 async function submit(event:FormEvent){event.preventDefault();if(!editor)return;setSaving(true);setError('');try{const{id,...draft}=editor;const saved=id?await updateUser(id,draft):await createUser(draft);setUsers(current=>id?current.map(user=>user.id===id?saved:user):[...current,saved]);setEditor(null)}catch(cause){setError(cause instanceof UsersApiError?cause.message:'Не удалось сохранить пользователя')}finally{setSaving(false)}}
 async function remove(user:UserRecord){if(!window.confirm(`Удалить пользователя «${user.name}»?`))return;setError('');try{await deleteUser(user.id);setUsers(current=>current.filter(item=>item.id!==user.id))}catch(cause){setError(cause instanceof UsersApiError?cause.message:'Не удалось удалить пользователя')}}
 if(parent)return <ParentChildrenView parent={parent} onBack={()=>setParent(null)}/>
 return <div className="content-stack"><div className="content-heading"><div><p className="content-kicker">Управление доступом</p><h2>Пользователи</h2></div><button className="primary-action" type="button" aria-label="Создать пользователя" onClick={()=>open()}>+ Создать пользователя</button></div>
 {error&&<p className="content-error" role="alert">{error}</p>}
 {loading?<div className="empty-card">Загружаем пользователей…</div>:<div className="table-card table-scroll"><table className="roles-table users-table"><thead><tr><th>Пользователь</th><th>Логин</th><th>Email / телефон</th><th>Роли</th><th>Статус</th><th><span className="visually-hidden">Действия</span></th></tr></thead><tbody>
 {users.map(user=><tr key={user.id}><td><strong>{user.name}</strong></td><td>{user.login??"—"}</td><td>{[user.email,user.phone].filter(Boolean).join(" · ")||"—"}</td><td><div className="permission-tags">{user.roles.map(role=><span key={role}>{roles.find(item=>item.code===role)?.name??role}</span>)}</div></td><td><span className={`status-badge status-badge--${user.status}`}>{user.status==='active'?'Активен':'Заблокирован'}</span></td><td><div className="row-actions">{user.roles.includes('parent')&&<button type="button" aria-label={`Дети пользователя ${user.name}`} onClick={()=>setParent(user)}>Дети</button>}<button type="button" aria-label={`Изменить пользователя ${user.name}`} onClick={()=>open(user)}>Изменить</button><button className="danger-action" type="button" aria-label={`Удалить пользователя ${user.name}`} onClick={()=>remove(user)}>Удалить</button></div></td></tr>)}
 {!users.length&&<tr><td className="empty-cell" colSpan={6}>Пользователи ещё не созданы</td></tr>}</tbody></table></div>}
 {editor&&<div className="dialog-backdrop" role="presentation"><section className="role-dialog" role="dialog" aria-modal="true" aria-labelledby="user-dialog-title"><div className="dialog-heading"><h3 id="user-dialog-title">{editor.id?'Изменить пользователя':'Новый пользователь'}</h3><button type="button" aria-label="Закрыть" onClick={()=>setEditor(null)}>×</button></div>
 <form className="role-form" onSubmit={submit}><label>Имя<input value={editor.name} onChange={event=>setEditor({...editor,name:event.target.value})} required maxLength={200}/></label><label>Логин<input value={editor.login} onChange={event=>setEditor({...editor,login:event.target.value})} required/></label><div className="form-columns"><label>Email<input type="email" value={editor.email} onChange={event=>setEditor({...editor,email:event.target.value})} /></label><label>Телефон<input type="tel" value={editor.phone} onChange={event=>setEditor({...editor,phone:event.target.value})}/></label></div><label>{editor.id?'Новый пароль':'Пароль'}<input type="password" value={editor.password} onChange={event=>setEditor({...editor,password:event.target.value})} required={!editor.id} minLength={8} autoComplete="new-password" placeholder={editor.id?'Оставьте пустым, чтобы не менять':'Не менее 8 символов'}/></label><label>Статус<select value={editor.status} onChange={event=>setEditor({...editor,status:event.target.value as UserDraft['status']})}><option value="active">Активен</option><option value="blocked">Заблокирован</option></select></label>
 <fieldset><legend>Роли</legend><div className="permissions-grid">{roles.map(role=><label className="permission-option" key={role.id}><input type="checkbox" checked={editor.roles.includes(role.code)} onChange={()=>toggleRole(role.code)}/><span><strong>{role.name}</strong><code>{role.code}</code></span></label>)}</div></fieldset>
 <div className="dialog-actions"><button className="secondary-action" type="button" onClick={()=>setEditor(null)}>Отмена</button><button className="primary-action" type="submit" disabled={saving||editor.roles.length===0}>{saving?'Сохраняем…':'Сохранить'}</button></div></form></section></div>}
 </div>
}
