import{afterEach,describe,expect,it,vi}from'vitest'
import{cleanup,render,screen}from'@testing-library/react'
import userEvent from'@testing-library/user-event'
import UsersView from'./UsersView'
afterEach(()=>{cleanup();vi.restoreAllMocks()})
describe('users',()=>{
 it('loads users and shows CRUD controls',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(async input=>String(input).includes('/roles')?new Response(JSON.stringify({roles:[{id:crypto.randomUUID(),code:'teacher',name:'Учитель',permissions:[]}]}),{status:200,headers:{'Content-Type':'application/json'}}):new Response(JSON.stringify({items:[{id:crypto.randomUUID(),email:'teacher@example.com',name:'Анна'+' '+'Иванова',status:'active',roles:['teacher']}],total:1}),{status:200,headers:{'Content-Type':'application/json'}}));render(<UsersView/>);expect(await screen.findByText('Анна Иванова')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Создать пользователя'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Изменить пользователя Анна Иванова'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Удалить пользователя Анна Иванова'})).toBeInTheDocument()})
 it('creates a user',async()=>{vi.spyOn(globalThis,'fetch').mockImplementation(async(input,init)=>{if(init?.method==='POST')return new Response(JSON.stringify({user:{id:crypto.randomUUID(),login:'teacher',email:'new@example.com',name:'Иван'+' '+'Петров',status:'active',roles:['teacher']}}),{status:201,headers:{'Content-Type':'application/json'}});if(String(input).includes('/roles'))return new Response(JSON.stringify({roles:[{id:crypto.randomUUID(),code:'teacher',name:'Учитель',permissions:[]}]}),{status:200,headers:{'Content-Type':'application/json'}});return new Response(JSON.stringify({items:[],total:0}),{status:200,headers:{'Content-Type':'application/json'}})});render(<UsersView/>);await screen.findByText('Пользователи ещё не созданы');await userEvent.click(screen.getByRole('button',{name:'Создать пользователя'}));await userEvent.type(screen.getByLabelText('Имя'),'Иван Петров');await userEvent.type(screen.getByLabelText('Логин'),'teacher');await userEvent.type(screen.getByLabelText('Email'),'new@example.com');await userEvent.type(screen.getByLabelText('Пароль'),'x');await userEvent.click(screen.getByText('Учитель'));await userEvent.click(screen.getByRole('button',{name:'Сохранить'}));expect(await screen.findByText('Иван Петров')).toBeInTheDocument()})
})
